language: java
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cat;'
  - mysql -u root --password="" cat < script/CatApplication.sql
  - mkdir -p $HOME/data/appdatas/cat && mkdir -p $HOME/data/applogs
  - cp ./docker/datasources.xml $HOME/data/appdatas/cat && export MYSQL_URL="127.0.0.1" && export MYSQL_PORT="13306" && export MYSQL_USERNAME="root"  && export MYSQL_PASSWD="" &&  export MYSQL_SCHEMA="cat" && sed "s# /data/# $HOME/data/#g" ./docker/datasources.sh > $HOME/data/datasources.sh && sh $HOME/data/datasources.sh
install:
  export CAT_HOME=$HOME/data/appdatas/cat && mvn install -Dmaven.test.skip -B -fae
script:
  export CAT_HOME=$HOME/data/appdatas/cat && mvn test -B -fae
