# mail@dongguochao.com

version: '2.2'

services:
  cat:
    container_name: cat
    # build from ./Dockerfile
    build: .
    environment:
      # if you have your own mysql, config it here, and disable the 'mysql' config blow
      - MYSQL_URL=cat-mysql # links will maintain /etc/hosts, just use 'container_name'
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWD=
      - MYSQL_SCHEMA=cat

    working_dir: /app
    privileged: true
    command: /bin/sh -c 'catalina.sh run'
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "2280:2280"

  # disable this if you have your own mysql
  mysql:
    container_name: cat-mysql
    image: mysql:5.7.22
    # expose 33306 to client (navicat)
    ports:
       - 33306:3306
    volumes:
      # change './docker/mysql/volume' to your own path
      # WARNING: without this line, your data will be lost.
      - "./docker/mysql/volume:/var/lib/mysql"
      # 第一次启动，可以通过命令创建数据库表 ：
      #                     docker exec 容器id bash -c "mysql -uroot -Dcat < /init.sql"
      - "./script/CatApplication.sql:/init.sql"
    command: mysqld -uroot --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "cat"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
